//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeMarketApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SharedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FreeMarketApp.Resources.SharedResources", typeof(SharedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to fill all fields and add at least one photo..
        /// </summary>
        internal static string Dialog_AddEditProduct_EmptyForm {
            get {
                return ResourceManager.GetString("Dialog_AddEditProduct_EmptyForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you want to leave this item?.
        /// </summary>
        internal static string Dialog_Confirmation_Cancel {
            get {
                return ResourceManager.GetString("Dialog_Confirmation_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you want to save this item? Changes will be propagated in next block (&quot;approx {0} sec&quot;)..
        /// </summary>
        internal static string Dialog_Confirmation_SaveMyItem {
            get {
                return ResourceManager.GetString("Dialog_Confirmation_SaveMyItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you want to save profile? Changes will be propagated in next block (&quot;approx {0} sec&quot;)..
        /// </summary>
        internal static string Dialog_Confirmation_SaveMyProfile {
            get {
                return ResourceManager.GetString("Dialog_Confirmation_SaveMyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        internal static string Dialog_Confirmation_Title {
            get {
                return ResourceManager.GetString("Dialog_Confirmation_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your description contains invalid chars..
        /// </summary>
        internal static string Dialog_FirstRun_InvalidCharsDescription {
            get {
                return ResourceManager.GetString("Dialog_FirstRun_InvalidCharsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password contains invalid chars..
        /// </summary>
        internal static string Dialog_FirstRun_InvalidCharsPassword {
            get {
                return ResourceManager.GetString("Dialog_FirstRun_InvalidCharsPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your seed contains invalid chars..
        /// </summary>
        internal static string Dialog_FirstRun_InvalidCharsSeed {
            get {
                return ResourceManager.GetString("Dialog_FirstRun_InvalidCharsSeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your username contains invalid chars..
        /// </summary>
        internal static string Dialog_FirstRun_InvalidCharsUserName {
            get {
                return ResourceManager.GetString("Dialog_FirstRun_InvalidCharsUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords aren&apos;t identical..
        /// </summary>
        internal static string Dialog_FirstRun_PasswordNotIdentical {
            get {
                return ResourceManager.GetString("Dialog_FirstRun_PasswordNotIdentical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your description is too short. Minimum is 50 chars..
        /// </summary>
        internal static string Dialog_FirstRun_ShortDescription {
            get {
                return ResourceManager.GetString("Dialog_FirstRun_ShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password is too short. Minimum is 16 chars..
        /// </summary>
        internal static string Dialog_FirstRun_ShortPassword {
            get {
                return ResourceManager.GetString("Dialog_FirstRun_ShortPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your seed is too short. Minimum is 200 chars..
        /// </summary>
        internal static string Dialog_FirstRun_ShortSeed {
            get {
                return ResourceManager.GetString("Dialog_FirstRun_ShortSeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your username is too short. Minimum is 10 chars..
        /// </summary>
        internal static string Dialog_FirstRun_ShortUserName {
            get {
                return ResourceManager.GetString("Dialog_FirstRun_ShortUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string Dialog_Information_Title {
            get {
                return ResourceManager.GetString("Dialog_Information_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password contains invalid chars..
        /// </summary>
        internal static string Dialog_LoginPage_InvalidCharsPassword {
            get {
                return ResourceManager.GetString("Dialog_LoginPage_InvalidCharsPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password is too short. Minimum is 16 chars..
        /// </summary>
        internal static string Dialog_LoginPage_ShortPassword {
            get {
                return ResourceManager.GetString("Dialog_LoginPage_ShortPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password was wrong. Try it again. Please..
        /// </summary>
        internal static string Dialog_LoginPage_WatermarkWrongPassword {
            get {
                return ResourceManager.GetString("Dialog_LoginPage_WatermarkWrongPassword", resourceCulture);
            }
        }
    }
}
