//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeMarketApp.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SharedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FreeMarketApp.Resources.SharedResources", typeof(SharedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit Listing.
        /// </summary>
        internal static string AddEditProduct_EditPageName {
            get {
                return ResourceManager.GetString("AddEditProduct_EditPageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Description contains banned words..
        /// </summary>
        internal static string Dialog_AddEditProduct_BannedWordsShortDescription {
            get {
                return ResourceManager.GetString("Dialog_AddEditProduct_BannedWordsShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Title contains banned words..
        /// </summary>
        internal static string Dialog_AddEditProduct_BannedWordsShortTitle {
            get {
                return ResourceManager.GetString("Dialog_AddEditProduct_BannedWordsShortTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You have to choose right category..
        /// </summary>
        internal static string Dialog_AddEditProduct_EmptyCategory {
            get {
                return ResourceManager.GetString("Dialog_AddEditProduct_EmptyCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You have to choose right deal type..
        /// </summary>
        internal static string Dialog_AddEditProduct_EmptyDealValue {
            get {
                return ResourceManager.GetString("Dialog_AddEditProduct_EmptyDealValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fineness info is too short..
        /// </summary>
        internal static string Dialog_AddEditProduct_EmptyFineness {
            get {
                return ResourceManager.GetString("Dialog_AddEditProduct_EmptyFineness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You have to fill all the fields and add at least one photo..
        /// </summary>
        internal static string Dialog_AddEditProduct_EmptyForm {
            get {
                return ResourceManager.GetString("Dialog_AddEditProduct_EmptyForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Manufacturer info is too short..
        /// </summary>
        internal static string Dialog_AddEditProduct_EmptyManufacturer {
            get {
                return ResourceManager.GetString("Dialog_AddEditProduct_EmptyManufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You have to add at least one photo..
        /// </summary>
        internal static string Dialog_AddEditProduct_EmptyPhoto {
            get {
                return ResourceManager.GetString("Dialog_AddEditProduct_EmptyPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You have to choose right price type..
        /// </summary>
        internal static string Dialog_AddEditProduct_EmptyPriceType {
            get {
                return ResourceManager.GetString("Dialog_AddEditProduct_EmptyPriceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на XRC Receiving Address is too short..
        /// </summary>
        internal static string Dialog_AddEditProduct_EmptyTBXRCReceivingAddress {
            get {
                return ResourceManager.GetString("Dialog_AddEditProduct_EmptyTBXRCReceivingAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Description contains invalid chars..
        /// </summary>
        internal static string Dialog_AddEditProduct_InvalidCharsDescription {
            get {
                return ResourceManager.GetString("Dialog_AddEditProduct_InvalidCharsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fineness field contains invalid chars..
        /// </summary>
        internal static string Dialog_AddEditProduct_InvalidCharsFineness {
            get {
                return ResourceManager.GetString("Dialog_AddEditProduct_InvalidCharsFineness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Manufacturer field contains invalid chars..
        /// </summary>
        internal static string Dialog_AddEditProduct_InvalidCharsManufacturer {
            get {
                return ResourceManager.GetString("Dialog_AddEditProduct_InvalidCharsManufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Price can contain numbers only..
        /// </summary>
        internal static string Dialog_AddEditProduct_InvalidCharsPrice {
            get {
                return ResourceManager.GetString("Dialog_AddEditProduct_InvalidCharsPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Shipping info contains invalid chars..
        /// </summary>
        internal static string Dialog_AddEditProduct_InvalidCharsShipping {
            get {
                return ResourceManager.GetString("Dialog_AddEditProduct_InvalidCharsShipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Description contains invalid chars..
        /// </summary>
        internal static string Dialog_AddEditProduct_InvalidCharsShortDescription {
            get {
                return ResourceManager.GetString("Dialog_AddEditProduct_InvalidCharsShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Shipping info contains invalid chars..
        /// </summary>
        internal static string Dialog_AddEditProduct_InvalidCharsShortShipping {
            get {
                return ResourceManager.GetString("Dialog_AddEditProduct_InvalidCharsShortShipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Title contains invalid chars..
        /// </summary>
        internal static string Dialog_AddEditProduct_InvalidCharsShortTitle {
            get {
                return ResourceManager.GetString("Dialog_AddEditProduct_InvalidCharsShortTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Size info contains invalid chars..
        /// </summary>
        internal static string Dialog_AddEditProduct_InvalidCharsSize {
            get {
                return ResourceManager.GetString("Dialog_AddEditProduct_InvalidCharsSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на XRC receiving address contains invalid chars..
        /// </summary>
        internal static string Dialog_AddEditProduct_InvalidCharsTBXRCReceivingAddress {
            get {
                return ResourceManager.GetString("Dialog_AddEditProduct_InvalidCharsTBXRCReceivingAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Title contains invalid chars..
        /// </summary>
        internal static string Dialog_AddEditProduct_InvalidCharsTitle {
            get {
                return ResourceManager.GetString("Dialog_AddEditProduct_InvalidCharsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Title is too short. Minimum is 50 chars..
        /// </summary>
        internal static string Dialog_AddEditProduct_ShortDescription {
            get {
                return ResourceManager.GetString("Dialog_AddEditProduct_ShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Price is too short. Minimum is 1 number and it can&apos;t be a zero..
        /// </summary>
        internal static string Dialog_AddEditProduct_ShortPrice {
            get {
                return ResourceManager.GetString("Dialog_AddEditProduct_ShortPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Shipping info is too short. Minimum is 10 chars..
        /// </summary>
        internal static string Dialog_AddEditProduct_ShortShipping {
            get {
                return ResourceManager.GetString("Dialog_AddEditProduct_ShortShipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Title is too short. Minimum is 10 chars..
        /// </summary>
        internal static string Dialog_AddEditProduct_ShortTitle {
            get {
                return ResourceManager.GetString("Dialog_AddEditProduct_ShortTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Description contains banned words..
        /// </summary>
        internal static string Dialog_ChatPage_BannedWordsDescription {
            get {
                return ResourceManager.GetString("Dialog_ChatPage_BannedWordsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Message contains invalid chars..
        /// </summary>
        internal static string Dialog_ChatPage_InvalidCharsMessage {
            get {
                return ResourceManager.GetString("Dialog_ChatPage_InvalidCharsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Message is too short..
        /// </summary>
        internal static string Dialog_ChatPage_ShortMessage {
            get {
                return ResourceManager.GetString("Dialog_ChatPage_ShortMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Are you sure that you want to buy this product? This step is irreversible. Changes will be propagated in next block (&quot;approx {0} sec&quot;)..
        /// </summary>
        internal static string Dialog_Confirmation_BuyProduct {
            get {
                return ResourceManager.GetString("Dialog_Confirmation_BuyProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Are you sure that you want to leave this item?.
        /// </summary>
        internal static string Dialog_Confirmation_Cancel {
            get {
                return ResourceManager.GetString("Dialog_Confirmation_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please provide product and seller review text..
        /// </summary>
        internal static string Dialog_Confirmation_PleaseProvideReviewText {
            get {
                return ResourceManager.GetString("Dialog_Confirmation_PleaseProvideReviewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please provide XRC transaction hash..
        /// </summary>
        internal static string Dialog_Confirmation_PleaseProvideXRCTransactionHash {
            get {
                return ResourceManager.GetString("Dialog_Confirmation_PleaseProvideXRCTransactionHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Are you sure that you want to remove this product? Changes will be propagated in the next block (&quot;approx {0} sec&quot;)..
        /// </summary>
        internal static string Dialog_Confirmation_RemoveProduct {
            get {
                return ResourceManager.GetString("Dialog_Confirmation_RemoveProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Posting a product seller/buyer review is ireversible. Are you sure you want to proceed?.
        /// </summary>
        internal static string Dialog_Confirmation_ReviewProduct {
            get {
                return ResourceManager.GetString("Dialog_Confirmation_ReviewProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Are you sure that you want to save this item? Changes will be propagated in the next block (&quot;approx {0} sec&quot;)..
        /// </summary>
        internal static string Dialog_Confirmation_SaveMyItem {
            get {
                return ResourceManager.GetString("Dialog_Confirmation_SaveMyItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Are you sure that you want to save profile? Changes will be propagated in the next block (&quot;approx {0} sec&quot;)..
        /// </summary>
        internal static string Dialog_Confirmation_SaveMyProfile {
            get {
                return ResourceManager.GetString("Dialog_Confirmation_SaveMyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Confirmation.
        /// </summary>
        internal static string Dialog_Confirmation_Title {
            get {
                return ResourceManager.GetString("Dialog_Confirmation_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Now wait for full propagation of this information to the network..
        /// </summary>
        internal static string Dialog_Confirmation_Waiting {
            get {
                return ResourceManager.GetString("Dialog_Confirmation_Waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You can&apos;t buy your own offer..
        /// </summary>
        internal static string Dialog_Confirmation_YouCantBuyYourOffer {
            get {
                return ResourceManager.GetString("Dialog_Confirmation_YouCantBuyYourOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This item exists in pool..
        /// </summary>
        internal static string Dialog_Error_Duplication {
            get {
                return ResourceManager.GetString("Dialog_Error_Duplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You need to have at least one peer to propagate transaction..
        /// </summary>
        internal static string Dialog_Error_NoMinimalPeer {
            get {
                return ResourceManager.GetString("Dialog_Error_NoMinimalPeer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Content of this item isn&apos;t valid with actual hash..
        /// </summary>
        internal static string Dialog_Error_NoValidContentHash {
            get {
                return ResourceManager.GetString("Dialog_Error_NoValidContentHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Item&apos;s changes are in the pool. Please wait for next block sychronization..
        /// </summary>
        internal static string Dialog_Error_StateOfItemIsInProgress {
            get {
                return ResourceManager.GetString("Dialog_Error_StateOfItemIsInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error.
        /// </summary>
        internal static string Dialog_Error_Title {
            get {
                return ResourceManager.GetString("Dialog_Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unexpected error during propagation of data. Please read application log..
        /// </summary>
        internal static string Dialog_Error_Unexpected {
            get {
                return ResourceManager.GetString("Dialog_Error_Unexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Content of action is wrong and can&apos;t be propagated..
        /// </summary>
        internal static string Dialog_Error_WrontTypeOfContent {
            get {
                return ResourceManager.GetString("Dialog_Error_WrontTypeOfContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Description contains banned words..
        /// </summary>
        internal static string Dialog_FirstRun_BannedWordsDescription {
            get {
                return ResourceManager.GetString("Dialog_FirstRun_BannedWordsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Description contains invalid chars..
        /// </summary>
        internal static string Dialog_FirstRun_InvalidCharsDescription {
            get {
                return ResourceManager.GetString("Dialog_FirstRun_InvalidCharsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password contains invalid chars..
        /// </summary>
        internal static string Dialog_FirstRun_InvalidCharsPassword {
            get {
                return ResourceManager.GetString("Dialog_FirstRun_InvalidCharsPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Seed contains invalid chars..
        /// </summary>
        internal static string Dialog_FirstRun_InvalidCharsSeed {
            get {
                return ResourceManager.GetString("Dialog_FirstRun_InvalidCharsSeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Username contains invalid chars..
        /// </summary>
        internal static string Dialog_FirstRun_InvalidCharsUserName {
            get {
                return ResourceManager.GetString("Dialog_FirstRun_InvalidCharsUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Passwords aren&apos;t identical..
        /// </summary>
        internal static string Dialog_FirstRun_PasswordNotIdentical {
            get {
                return ResourceManager.GetString("Dialog_FirstRun_PasswordNotIdentical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Description is too short. Minimum is 50 chars..
        /// </summary>
        internal static string Dialog_FirstRun_ShortDescription {
            get {
                return ResourceManager.GetString("Dialog_FirstRun_ShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password is too short. Minimum is 16 chars..
        /// </summary>
        internal static string Dialog_FirstRun_ShortPassword {
            get {
                return ResourceManager.GetString("Dialog_FirstRun_ShortPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Seed is too short. Minimum is 200 chars..
        /// </summary>
        internal static string Dialog_FirstRun_ShortSeed {
            get {
                return ResourceManager.GetString("Dialog_FirstRun_ShortSeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Username is too short. Minimum is 10 chars..
        /// </summary>
        internal static string Dialog_FirstRun_ShortUserName {
            get {
                return ResourceManager.GetString("Dialog_FirstRun_ShortUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You can send next message in 10 seconds..
        /// </summary>
        internal static string Dialog_Information_CantSendNextMessage {
            get {
                return ResourceManager.GetString("Dialog_Information_CantSendNextMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Restart application to see changes..
        /// </summary>
        internal static string Dialog_Information_ChangeTheme {
            get {
                return ResourceManager.GetString("Dialog_Information_ChangeTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You have to wait for the seller&apos;s answer..
        /// </summary>
        internal static string Dialog_Information_ChatWaitForAnswer {
            get {
                return ResourceManager.GetString("Dialog_Information_ChatWaitForAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Information.
        /// </summary>
        internal static string Dialog_Information_Title {
            get {
                return ResourceManager.GetString("Dialog_Information_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password contains invalid chars..
        /// </summary>
        internal static string Dialog_LoginPage_InvalidCharsPassword {
            get {
                return ResourceManager.GetString("Dialog_LoginPage_InvalidCharsPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password is too short. Minimum is 16 chars..
        /// </summary>
        internal static string Dialog_LoginPage_ShortPassword {
            get {
                return ResourceManager.GetString("Dialog_LoginPage_ShortPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Incorrect password. Please try again..
        /// </summary>
        internal static string Dialog_LoginPage_WatermarkWrongPassword {
            get {
                return ResourceManager.GetString("Dialog_LoginPage_WatermarkWrongPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Your review contains banned words..
        /// </summary>
        internal static string Dialog_Review_BannedWordsDescription {
            get {
                return ResourceManager.GetString("Dialog_Review_BannedWordsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Your profile.
        /// </summary>
        internal static string LoginPage_UserName_LoginName {
            get {
                return ResourceManager.GetString("LoginPage_UserName_LoginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на N/A.
        /// </summary>
        internal static string MarketCategory_Label_0 {
            get {
                return ResourceManager.GetString("MarketCategory_Label_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Gold.
        /// </summary>
        internal static string MarketCategory_Label_1 {
            get {
                return ResourceManager.GetString("MarketCategory_Label_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Silver.
        /// </summary>
        internal static string MarketCategory_Label_2 {
            get {
                return ResourceManager.GetString("MarketCategory_Label_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Platinum.
        /// </summary>
        internal static string MarketCategory_Label_3 {
            get {
                return ResourceManager.GetString("MarketCategory_Label_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rhodium.
        /// </summary>
        internal static string MarketCategory_Label_4 {
            get {
                return ResourceManager.GetString("MarketCategory_Label_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Palladium.
        /// </summary>
        internal static string MarketCategory_Label_5 {
            get {
                return ResourceManager.GetString("MarketCategory_Label_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Copper.
        /// </summary>
        internal static string MarketCategory_Label_6 {
            get {
                return ResourceManager.GetString("MarketCategory_Label_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rare Coins.
        /// </summary>
        internal static string MarketCategory_Label_7 {
            get {
                return ResourceManager.GetString("MarketCategory_Label_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Jewelry.
        /// </summary>
        internal static string MarketCategory_Label_8 {
            get {
                return ResourceManager.GetString("MarketCategory_Label_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cryptocurrency.
        /// </summary>
        internal static string MarketCategory_Label_9 {
            get {
                return ResourceManager.GetString("MarketCategory_Label_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на N/A.
        /// </summary>
        internal static string MarketDealType_Label_0 {
            get {
                return ResourceManager.GetString("MarketDealType_Label_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pay 0% before 100% after.
        /// </summary>
        internal static string MarketDealType_Label_1 {
            get {
                return ResourceManager.GetString("MarketDealType_Label_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pay 90% before 10% after.
        /// </summary>
        internal static string MarketDealType_Label_10 {
            get {
                return ResourceManager.GetString("MarketDealType_Label_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pay 100% before 0% after.
        /// </summary>
        internal static string MarketDealType_Label_11 {
            get {
                return ResourceManager.GetString("MarketDealType_Label_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pay 10% before 90% after.
        /// </summary>
        internal static string MarketDealType_Label_2 {
            get {
                return ResourceManager.GetString("MarketDealType_Label_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pay 20% before 80% after.
        /// </summary>
        internal static string MarketDealType_Label_3 {
            get {
                return ResourceManager.GetString("MarketDealType_Label_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pay 30% before 70% after.
        /// </summary>
        internal static string MarketDealType_Label_4 {
            get {
                return ResourceManager.GetString("MarketDealType_Label_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pay 40% before 60% after.
        /// </summary>
        internal static string MarketDealType_Label_5 {
            get {
                return ResourceManager.GetString("MarketDealType_Label_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pay 50% before 50% after.
        /// </summary>
        internal static string MarketDealType_Label_6 {
            get {
                return ResourceManager.GetString("MarketDealType_Label_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pay 60% before 40% after.
        /// </summary>
        internal static string MarketDealType_Label_7 {
            get {
                return ResourceManager.GetString("MarketDealType_Label_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pay 70% before 30% after.
        /// </summary>
        internal static string MarketDealType_Label_8 {
            get {
                return ResourceManager.GetString("MarketDealType_Label_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pay 80% before 20% after.
        /// </summary>
        internal static string MarketDealType_Label_9 {
            get {
                return ResourceManager.GetString("MarketDealType_Label_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на offline.
        /// </summary>
        internal static string State_Down {
            get {
                return ResourceManager.GetString("State_Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на online.
        /// </summary>
        internal static string State_Running {
            get {
                return ResourceManager.GetString("State_Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на N/A.
        /// </summary>
        internal static string UnknownValue {
            get {
                return ResourceManager.GetString("UnknownValue", resourceCulture);
            }
        }
    }
}
